# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f4c6b23877b7dddaa2abbdb0f9ae5898ee258143434b935da5ae59ea688bfef21232c125626a690ed7e4789c5ba34aeedbc7d20d1bd0d33692e16fe6b14797

test:
  secret_key_base: 0cad974d3927213c934aa234d47382586bfb86fe45f0d5525aab1325b92c5ab093875a4c24fe53603131c6af4471ba706392c190ba801a579f07f9cb4126c23f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
